server:
  port: 8081
spring:
  application:
    name: xzdp #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xzdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: 192.168.159.100
    port: 6379
    #password: 123321
    lettuce: #设置redis连接池
      pool:
        max-active: 10 #最大连接数
        max-idle: 10 #最大空闲连接
        min-idle: 0 #最小空闲连接
        time-between-eviction-runs: 10s #最长等待时间
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  #配置热部署
  devtools:
    restart:
      enabled: true

mybatis-plus:
  type-aliases-package: com.xzdp.entity # 别名扫描包

logging:
  level:
    com.xzdp: debug

